Added Vancouver
globalazure/communities pull request #134
Opened 2023-02-16 23:08 UTC by davidnudelman

2023-02-20 10:35 UTC, noopman requested changes
I am missing an .MD file with basic information about your community! Please refer to some of the other folders here to figure out who to make one! (Copy paste a file and change to match your community information!)

2023-02-20 10:35 UTC, noopman commented on 2023/AzureVancouver/data.json
> +      ""
Please enter the github user id's for any user who is allowed to edit this folder via a PR!

2023-02-20 10:35 UTC, noopman commented on 2023/AzureVancouver/data.json
> +    "SessionizeApiId": "{Your sessionize event Id}",
Either enter a valid Sessionize, or blank this field!

2023-02-21 18:04 UTC, davidnudelman commented
@noopman Done! Thanks for the help

2023-02-22 13:02 UTC, noopman commented
> @noopman Done! Thanks for the help

Hey there @davidnudelman ! I could still use resolutions to the review comments I made in your data.json file, specifically that you list any GH handles for the persons - at least yourself - who are valid maintainers of your community folder content!

2023-02-22 18:01 UTC, davidnudelman commented
Thank you, this should now be completed. This is all new to me!

2023-02-23 12:09 UTC, noopman approved these changes
This is perfect @davidnudelman , thanks for your diligence! Our review is to ensure your data is right and yields the intended results on the site. Thanks also for your patience!

2023-02-23 12:09 UTC, merged