Registering the Bangalore Azure community
globalazure/communities pull request #169
Opened 2023-03-20 13:32 UTC by Keshav1308

Registering the Bangalore Azure community

2023-03-21 19:13 UTC, noopman requested changes
Hello @Keshav1308 ! Thank you for your interest in Global Azure 2023 and for claiming your community pin on the map. As there are a few items missing from your submission, please review our [readme](https://github.com/globalazure/communities#global-azure-communities) to learn how to complete your registration.

We need a logo file, an index.md file and the data in your data.json needs a few fixes!

Thanks in advance!

2023-03-21 19:13 UTC, noopman commented on 2023/AzureBengaluru/data.json
> +      ""
We need the GitHub ID's of those users who are allowed to edit your folder! For example yours @Keshav1308

2023-03-21 19:13 UTC, noopman commented on 2023/AzureBengaluru/data.json
> +    "SessionizeApiId": "10862",
Are you sure this SessionizeID is accurate?

2023-03-21 19:13 UTC, noopman commented on 2023/AzureBengaluru/data.json
> +      "File": "AzureBengaluru.png"
This file is not present in your submission. Instead you have a file _template.png in the folder, and that is just a placeholder.

2023-03-22 09:38 UTC, noopman requested changes
This is looking very good indeed! Thanks for the progress on this @Keshav1308 and @samikroy.

1. Can you verify the "SeeionizeApiId" please. I'm not sure it looks right. When I check it the result is 404.
2. I need an index.md file in the folder for you! Please look in other folders next to yours for inspiration what other communities did!

2023-03-22 10:08 UTC, Keshav1308 commented
Thanks, Magnus, for looking into this.  attaching the index file. Use this latest index file please 🙂 .

This Sessionize ID is working for us https://sessionize.com/app/organizer/event/10862

[cid:bc859433-e6e1-4678-a8e0-37be573caadf]

________________________________
From: Magnus Mårtensson ***@***.***>
Sent: Wednesday, March 22, 2023 3:08 PM
To: globalazure/communities ***@***.***>
Cc: Keshav1308 ***@***.***>; Mention ***@***.***>
Subject: Re: [globalazure/communities] Registering the Bangalore Azure community (PR #169)


@noopman requested changes on this pull request.

This is looking very good indeed! Thanks for the progress on this @Keshav1308<https://github.com/Keshav1308> and @samikroy<https://github.com/samikroy>.

  1.  Can you verify the "SeeionizeApiId" please. I'm not sure it looks right. When I check it the result is 404.
  2.  I need an index.md file in the folder for you! Please look in other folders next to yours for inspiration what other communities did!

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/169#pullrequestreview-1352098809>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGDHQWEDPUPUXIPTYVTO6V3W5LCBHANCNFSM6AAAAAAWBC652E>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-22 10:13 UTC, noopman commented
> Thanks, Magnus, for looking into this. attaching the index file. This Sessionize ID is working for us https://sessionize.com/app/organizer/event/10862 [cid:bc859433-e6e1-4678-a8e0-37be573caadf]

@Keshav1308 this is still confounding me. Here is an example Sessionize ID that works: w84xg5cq. It can be verified by browsing to the API endpoint of the event like this: [https://sessionize.com/api/v2/w84xg5cq/view/Sessions](https://sessionize.com/api/v2/w84xg5cq/view/Sessions) The endpoint is present and shows that there are currently no published sessions at this event.

When I do the same with your ID this is the result: [https://sessionize.com/api/v2/10862/view/Sessions](https://sessionize.com/api/v2/10862/view/Sessions) 404!

I think you are using the event ID but not the API ID. Please look into your sessionize event and see if you can find the event's unique API ID!

2023-03-22 10:15 UTC, noopman commented
You also need, please, to add an index.md file to your folder in this PR!

2023-03-22 10:22 UTC, Keshav1308 commented
Adding Samik Roy.

Hi @***@***.******@***.***> ,

We need the event's unique API ID!

Regards,
Keshav Jain.
________________________________
From: Magnus Mårtensson ***@***.***>
Sent: Wednesday, March 22, 2023 3:45 PM
To: globalazure/communities ***@***.***>
Cc: Keshav1308 ***@***.***>; Mention ***@***.***>
Subject: Re: [globalazure/communities] Registering the Bangalore Azure community (PR #169)


You also need, please, to add an index.md file to your folder in this PR!

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/169#issuecomment-1479275741>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGDHQWFIHYYI53NHVO6HJGLW5LGK7ANCNFSM6AAAAAAWBC652E>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-03-22 14:35 UTC, noopman commented
Great with the index.md file. It looks very good. Now we only need to ensure you have the right Sessionize API ID in the file!

2023-03-22 15:43 UTC, samikroy commented
> Great with the index.md file. It looks very good. Now we only need to ensure you have the right Sessionize API ID in the file!

@noopman  - Thank you for sharing this.
Could you please have a look if this one you are looing for
https://sessionize.com/api/v2/o6kupum9/view/Sessions
CC- @Keshav1308

2023-03-22 21:48 UTC, noopman approved these changes
That sessionizeid looks right @Keshav1308 and @samikroy ! I went ahead and added it to your data.json file for you, and am now approving your PR! Thanks for joining Global Azure!

2023-03-22 21:49 UTC, merged