Made changes specific to Charlotte Azure Event
globalazure/communities pull request #181
Opened 2023-03-24 13:47 UTC by nirajrules

2023-03-25 07:47 UTC, noopman requested changes
I am missing an index.md file in this submission, please, @nirajrules @ashishmgupta.

2023-03-25 07:47 UTC, noopman commented on 2023/CharlotteMicrosoftAzure/data.json
> +    "SessionizeApiId": "{Your sessionize event Id}",
Are you planning to use Sessionize to show off your community's sessions on the global azure site?

2023-03-26 09:18 UTC, noopman commented
*Ping* @nirajrules @ashishmgupta !

2023-04-19 15:31 UTC, tiagocostapt commented
@nirajrules do you still want to move this PR forward?

2023-04-21 13:09 UTC, noopman commented
I pinged @ashishmgupta on LinkedIn.

2023-05-20 09:28 UTC, noopman commented
Closing this due to inactivity!

2023-05-20 09:28 UTC, closed without merging