data.json
globalazure/communities pull request #226
Opened 2023-04-07 07:09 UTC by CodeSizzler

2023-04-07 07:21 UTC, noopman requested changes
I am missing an index.md file in this same folder! Look at other folders next to this one and get inspiration for your own index.md!

2023-04-07 07:21 UTC, noopman commented on 2023/DearAzure/data.json
> +      "",
You need to add your handle @CodeSizzler here, to make you a valid maintainer of this folder!

2023-04-07 07:21 UTC, noopman commented on 2023/DearAzure/data.json
> +    "SessionizeApiId": "{Your sessionize event Id}",
Will you be using Sessionize to show off your event sessions on globalazure.net?

2023-04-07 07:21 UTC, noopman commented on 2023/DearAzure/data.json
> +      "File": "dearazure.png"
You need to add your logo file to the same folder and name it dearazure.png!

2023-04-19 15:30 UTC, tiagocostapt commented
@CodeSizzler any updates? Do you still want to update your event with this PR?

2023-04-21 13:12 UTC, closed without merging