Adding My Community
globalazure/communities pull request #313
Opened 2023-10-29 19:10 UTC by itstalmeez

I am adding my community to Global Azure

2023-10-30 15:47 UTC, noopman requested changes
This is not right. You need to have your files in a subfolder with your community name. Sorry for the confusion. Please review https://github.com/globalazure/communities/blob/main/README.md

2023-11-01 17:46 UTC, itstalmeez commented
Check now

2023-11-02 05:18 UTC, itstalmeez commented
@noopman Did you check?

2023-11-02 09:58 UTC, noopman commented
Haha, no not yet, I didn't.

2023-11-02 10:01 UTC, noopman requested changes
A few more changes and we're there! Good work!

2023-11-02 10:01 UTC, noopman commented on 2024/Tech Empire/data.json
If you have an adress, then maybe you can also add the lon/lat for the location, please? This is how the map finds the location. Compare with https://github.com/globalazure/communities/blob/main/2024/azureskane/data.json

2023-11-02 14:22 UTC, itstalmeez commented
Okay check now

2023-11-03 13:03 UTC, itstalmeez commented
@noopman heyyyyyy!!!!!!!! I think so I've done.

2023-11-06 09:13 UTC, noopman commented
@itstalmeez your PR contains double the files. BOTH in the /2024 folder AND in your community subfolder. You need to remove the marked files below from this PR, please!

![image](https://github.com/globalazure/communities/assets/300622/436e4e27-e144-4097-bc1e-66f34028cba1)

2023-11-06 15:42 UTC, itstalmeez commented
@noopman Check now

2023-11-06 15:44 UTC, noopman approved these changes
That's it! Perfect, thanks.

2023-11-06 15:45 UTC, merged