Create Data.json
globalazure/communities pull request #35
Opened 2022-03-25 13:02 UTC by agussuparno

2022-03-28 10:36 UTC, noopman requested changes
Hello there! Please follow the instructions in the repo readme file, and please ask if you have additional questions!

2022-03-29 22:11 UTC, agussuparno commented
I have already pull request.
Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Magnus Mårtensson ***@***.***>
Sent: Monday, March 28, 2022 5:36:40 PM
To: globalazure/communities ***@***.***>
Cc: Agus Suparno ***@***.***>; Author ***@***.***>
Subject: Re: [globalazure/communities] Create Data.json (PR #35)


@noopman requested changes on this pull request.

Hello there! Please follow the instructions in the repo readme file, and please ask if you have additional questions!

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/35#pullrequestreview-922943361>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACH5ZWFTSJLZVCWVVGEZP4LVCGDTRANCNFSM5RUDGKHQ>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-04-19 06:26 UTC, noopman commented
Hello @agussuparno how are things going for Global Azure on your end? We have had on update on this PR for a while and therefor I am reaching out to ask if I can help you somehow? If you do not need this PR we will close it in a few days!

2022-04-19 19:24 UTC, agussuparno commented
Thanks, Magnus for your support.
My problems are solved.

Regards,
Agus
________________________________
From: Magnus Mårtensson ***@***.***>
Sent: Tuesday, April 19, 2022 1:26 PM
To: globalazure/communities ***@***.***>
Cc: Agus Suparno ***@***.***>; Mention ***@***.***>
Subject: Re: [globalazure/communities] Create Data.json (PR #35)


Hello @agussuparno<https://github.com/agussuparno> how are things going for Global Azure on your end? We have had on update on this PR for a while and therefor I am reaching out to ask if I can help you somehow? If you do not need this PR we will close it in a few days!

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/35#issuecomment-1102141861>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACH5ZWCKTVPSGCU23PMKHPTVFZGZXANCNFSM5RUDGKHQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-04-22 05:24 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +      "",
There needs to be a list here of the valid folder-maintainers!

2022-04-22 05:28 UTC, noopman commented
I am missing a file called index.md in your community folder! Please look at the other contributions and emulate something similar!

2022-04-22 05:29 UTC, noopman requested changes
You need to please look at the other community folders and also read this repo's reademe.md to see what it is you need to do! Thank you!

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +    "GitHubHandles": [
There needs to be a list here of the valid folder-maintainers!

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +    "SessionizeApiId": "{7751}",
This is not a valid ApiId!

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +        "Name": "{Mugi Purwokerto}",
You should not have { } in your entries! Just the text.

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +        "Address": "{Jl. Adipura VI No. 228, Purwosari, Baturaden, Central Java Indonesia}",
You should not have { } in your entries! Just the text.

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +      "File": "_template.png"
Would you like to add your community logo to the folder and reference it here?

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
You should not have { } in your entries! Just the text.

2022-04-22 05:29 UTC, noopman commented on 2022/MugiPurwokerto/Data.json
> +    "Country": "{Indonesia}",
You should not have { } in your entries! Just the text.

2022-04-22 05:35 UTC, agussuparno commented
Okay, I will change it.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Magnus Mårtensson ***@***.***>
Sent: Friday, April 22, 2022 12:29:32 PM
To: globalazure/communities ***@***.***>
Cc: Agus Suparno ***@***.***>; Mention ***@***.***>
Subject: Re: [globalazure/communities] Create Data.json (PR #35)


@noopman requested changes on this pull request.

You need to please look at the other community folders and also read this repo's reademe.md to see what it is you need to do! Thank you!

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855776459>:

> @@ -0,0 +1,28 @@
+{
+  "ValidMaintainers": {
+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",
+    "GitHubHandles": [


There needs to be a list here of the valid folder-maintainers!

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855776716>:

> @@ -0,0 +1,28 @@
+{
+  "ValidMaintainers": {
+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",
+    "GitHubHandles": [
+      "",
+      "",
+      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
+    "Country": "{Indonesia}",
+    "Url": "https://mugipurwokerto.or.id/",
+    "SessionizeApiId": "{7751}",


This is not a valid ApiId!

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777058>:

> +      "",
+      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
+    "Country": "{Indonesia}",
+    "Url": "https://mugipurwokerto.or.id/",
+    "SessionizeApiId": "{7751}",
+    "Logo": {
+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",
+      "File": "_template.png"
+    },
+    "Locations": [
+      {
+        "Name": "{Mugi Purwokerto}",


You should not have { } in your entries! Just the text.

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777081>:

> +      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
+    "Country": "{Indonesia}",
+    "Url": "https://mugipurwokerto.or.id/",
+    "SessionizeApiId": "{7751}",
+    "Logo": {
+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",
+      "File": "_template.png"
+    },
+    "Locations": [
+      {
+        "Name": "{Mugi Purwokerto}",
+        "Address": "{Jl. Adipura VI No. 228, Purwosari, Baturaden, Central Java Indonesia}",


You should not have { } in your entries! Just the text.

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777217>:

> +  "ValidMaintainers": {
+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",
+    "GitHubHandles": [
+      "",
+      "",
+      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
+    "Country": "{Indonesia}",
+    "Url": "https://mugipurwokerto.or.id/",
+    "SessionizeApiId": "{7751}",
+    "Logo": {
+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",
+      "File": "_template.png"


Would you like to add your community logo to the folder and reference it here?

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777277>:

> @@ -0,0 +1,28 @@
+{
+  "ValidMaintainers": {
+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",
+    "GitHubHandles": [
+      "",
+      "",
+      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",


You should not have { } in your entries! Just the text.

________________________________

In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777297>:

> @@ -0,0 +1,28 @@
+{
+  "ValidMaintainers": {
+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",
+    "GitHubHandles": [
+      "",
+      "",
+      ""
+    ]
+  },
+  "CommunityInfo": {
+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",
+    "Country": "{Indonesia}",


You should not have { } in your entries! Just the text.

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/35#pullrequestreview-949453726>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACH5ZWGVSYFZQQFC6TG34R3VGI2LZANCNFSM5RUDGKHQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-02-05 07:30 UTC, noopman commented
This was a leftover from last year. Closing it.

2023-02-05 07:30 UTC, closed without merging

2023-03-07 21:10 UTC, agussuparno commented
Hi Magnus,
I just pull request to github for Global Azure Indonesia 2023.
Could you please review it.

Thank you,

Agus Suparno

From: Agus ***@***.***>
Sent: Jumat, 22 April 2022 12.35
To: ***@***.***>; ***@***.***>
Cc: ***@***.***>
Subject: Re: [globalazure/communities] Create Data.json (PR #35)

Okay, I will change it.

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>

From: Magnus Mårtensson ***@***.***>
Sent: Friday, April 22, 2022 12:29:32 PM
To: globalazure/communities ***@***.***>
Cc: Agus Suparno ***@***.***>; Mention ***@***.***>
Subject: Re: [globalazure/communities] Create Data.json (PR #35)


@noopman requested changes on this pull request.

You need to please look at the other community folders and also read this repo's reademe.md to see what it is you need to do! Thank you!


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855776459>:

> @@ -0,0 +1,28 @@

+{

+  "ValidMaintainers": {

+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",

+    "GitHubHandles": [

There needs to be a list here of the valid folder-maintainers!


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855776716>:

> @@ -0,0 +1,28 @@

+{

+  "ValidMaintainers": {

+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",

+    "GitHubHandles": [

+      "",

+      "",

+      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

+    "Country": "{Indonesia}",

+    "Url": "https://mugipurwokerto.or.id/",

+    "SessionizeApiId": "{7751}",

This is not a valid ApiId!


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777058>:

> +      "",

+      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

+    "Country": "{Indonesia}",

+    "Url": "https://mugipurwokerto.or.id/",

+    "SessionizeApiId": "{7751}",

+    "Logo": {

+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",

+      "File": "_template.png"

+    },

+    "Locations": [

+      {

+        "Name": "{Mugi Purwokerto}",

You should not have { } in your entries! Just the text.


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777081>:

> +      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

+    "Country": "{Indonesia}",

+    "Url": "https://mugipurwokerto.or.id/",

+    "SessionizeApiId": "{7751}",

+    "Logo": {

+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",

+      "File": "_template.png"

+    },

+    "Locations": [

+      {

+        "Name": "{Mugi Purwokerto}",

+        "Address": "{Jl. Adipura VI No. 228, Purwosari, Baturaden, Central Java Indonesia}",

You should not have { } in your entries! Just the text.


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777217>:

> +  "ValidMaintainers": {

+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",

+    "GitHubHandles": [

+      "",

+      "",

+      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

+    "Country": "{Indonesia}",

+    "Url": "https://mugipurwokerto.or.id/",

+    "SessionizeApiId": "{7751}",

+    "Logo": {

+      "Description": "Community logo is a .png file 500X500px named {foldername}.png.",

+      "File": "_template.png"

Would you like to add your community logo to the folder and reference it here?


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777277>:

> @@ -0,0 +1,28 @@

+{

+  "ValidMaintainers": {

+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",

+    "GitHubHandles": [

+      "",

+      "",

+      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

You should not have { } in your entries! Just the text.


In 2022/MugiPurwokerto/Data.json<https://github.com/globalazure/communities/pull/35#discussion_r855777297>:

> @@ -0,0 +1,28 @@

+{

+  "ValidMaintainers": {

+    "Description": "GitHub users who maintain this folder. PR for changing this folder will only be accepted from these users.",

+    "GitHubHandles": [

+      "",

+      "",

+      ""

+    ]

+  },

+  "CommunityInfo": {

+    "Name": "{Microsoft User Group Indonesia (Mugi) Purwokerto}",

+    "Country": "{Indonesia}",

You should not have { } in your entries! Just the text.

—
Reply to this email directly, view it on GitHub<https://github.com/globalazure/communities/pull/35#pullrequestreview-949453726>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACH5ZWGVSYFZQQFC6TG34R3VGI2LZANCNFSM5RUDGKHQ>.
You are receiving this because you were mentioned.Message ID: ***@***.***>