Add_globalazurevirtualkorea
globalazure/communities pull request #53
Opened 2022-04-06 01:31 UTC by kimsejun2000

Global Azure Virtual 2022 on Korea will be hosted by Korea Azure User Group and Wise Azure Life.
This event is a local event and sessions will be held in Korean.
4 tracks and 17 speakers.

2022-04-06 01:34 UTC, kimsejun2000 commented
Links linked are temporary. It will be updated soon.

2022-04-06 07:25 UTC, noopman requested changes
Just a tiny change needed. All else looks very good!

2022-04-06 07:25 UTC, noopman commented on 2022/globalazurekorea/data.json
> +    "Country": "Seoul",
Seoul is a city. Please put country!

2022-04-06 07:26 UTC, noopman commented
> Global Azure Virtual 2022 on Korea will be hosted by Korea Azure User Group and Wise Azure Life. This event is a local event and sessions will be held in Korean. 4 tracks and 17 speakers.

THAT is AWESOME! Can't wait to get you on the site and I will make lots of noise about it too! Welcome to Global Azure OUR league of communities!

2022-04-06 23:44 UTC, kimsejun2000 commented
I modified Country with your help.

2022-04-07 00:49 UTC, noopman approved these changes
That's perfect @kimsejun2000 merging your request now! Welcome to the league of extraordinary global azure communities! :D

2022-04-07 00:50 UTC, merged