Added azure meetup frankfurt
globalazure/communities pull request #57
Opened 2022-04-06 16:43 UTC by ddobric

:)

2022-04-06 17:44 UTC, noopman requested changes

2022-04-06 17:44 UTC, noopman commented on 2022/AzureMeetupFrankfurt/index.md
> +![DotNetFriday](dnf.png)
This file reference does not work. Should it be dotnetfriday.png perhaps?

2022-04-06 17:49 UTC, noopman commented
Nice to see your face by the way @ddobric ! :D

2022-04-06 22:44 UTC, closed without merging

2022-04-06 22:44 UTC, ddobric commented
will correct

2022-04-08 11:38 UTC, davidjrh commented
Hi @ddobric , seems there is an issue with your Sessionize API endpoint. Is currently returning a javascript response instead of the expected JSON when browsing https://sessionize.com/api/v2/pslfsnw6/view/Sessions, so the sessions are not being populated on the Global website.

Can you recheck the instructions at https://blog.globalazure.net/Blog/Post/284/Sessionize-integration-setup-for-local-event-organizers-for-2022-edition and that when browsing the Sessions List URL:
* ensure the result is in JSON format (if not, review the settings mentioned in the previous section)
* ensure the "startsAt" and "endsAt" are populated with date values between May 5th and May 7th

2022-04-28 08:47 UTC, ddobric commented
Now it seems to deliver the JSON.

2022-04-28 08:50 UTC, davidjrh commented
Hi again @ddobric, can you doble check again the setup and review the parameters? The startsAt and EndsAt fields are coming as null. Ensure you have setup the sessions on the Sessionize scheduler to allow these fields being populated.